CREATE TABLE `games` ( `win_points`   INTEGER NOT NULL,  `word_count`    INTEGER NOT NULL);
CREATE TABLE `lists`   ( `_id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `name` VARCHAR (255) NOT NULL, `selected` BOOLEAN DEFAULT 0 );
CREATE TABLE `words`   ( `_id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `word` VARCHAR (255) NOT NULL, `used_location` INTEGER DEFAULT -1, `list_id` INTEGER NOT NULL, CONSTRAINT fk_list_id FOREIGN KEY (list_id) REFERENCES lists (_id) ON DELETE CASCADE );
CREATE TABLE `teams`  ( `_id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `name` VARCHAR (255) NOT NULL);
CREATE TABLE `players` ( `_id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `name` VARCHAR (255) NOT NULL, `team_id` INTEGER NOT NULL, CONSTRAINT fk_team_id FOREIGN KEY (team_id) REFERENCES `groups` (_id) ON DELETE CASCADE);
CREATE TABLE `favorites` ( `name` VARCHAR (255) NOT NULL PRIMARY KEY);
CREATE TABLE `scores`  ( `team_id` INTEGER NOT NULL PRIMARY KEY, `score` INTEGER DEFAULT 0, CONSTRAINT fk_team_id FOREIGN KEY (team_id) REFERENCES `teams` (_id) ON DELETE CASCADE);
