INSERT INTO games (win_points, word_count) VALUES (20, 5);
INSERT INTO lists (_id, name, selected) VALUES (1, 'Surprise 2017', 1);
INSERT INTO words (word, list_id) VALUES ("Rowwen Hèze", 1), ("Brouwenrij", 1), ("Donald Duck", 1), ("Hostie", 1), ("Gilde opleidingen", 1), ("Fumble", 1), ("Untappd", 1), ("Midden in de nacht Rick", 1);
INSERT INTO words (word, list_id) VALUES ("Green Bay Packers", 1), ("Super bowl", 1), ("Halftime show", 1), ("Goesting Craft Beer Festival", 1), ("Vrienden weekend", 1), ("Tap takeover", 1);
INSERT INTO words (word, list_id) VALUES ("Goesting", 1), ("McTain", 1), ("Aaron Rodgers", 1), ("Ziekencommunie", 1), ("Bollie", 1), ("Maasdijk", 1), ("Tafeltennis", 1), ("OBS De Landweert", 1);
INSERT INTO words (word, list_id) VALUES ("Boterbloem", 1), ("IDent!ty", 1), ("Sinas", 1), ("Hardlopen", 1), ("Gameboy", 1), ("Gamecube", 1), ("HTC", 1), ("Nokia", 1), ("OnePlus", 1), ("Wii", 1);
INSERT INTO words (word, list_id) VALUES ("SNES mini", 1), ("Zelda", 1), ("Wind waker", 1), ("Navi", 1), ("Mario en Luigi", 1), ("Netflix", 1), ("Spotify", 1);
INSERT INTO words (word, list_id) VALUES ("1 november 2016", 1), ("Shannon song", 1), ("30 jaar", 1), ("Price Cleaning", 1), ("Raayland", 1), ("Bronckhorster", 1), ("Hertog Jan", 1), ("Barleywine", 1);
INSERT INTO words (word, list_id) VALUES ("Põhjala", 1), ("Stout", 1), ("Straffe Hendrik", 1), ("Jopen", 1), ("Kruistocht Van Thomas", 1), ("kwestie van geduld", 1), ("Heilige hopjes", 1), ("HOnNEbrUW", 1);
INSERT INTO words (word, list_id) VALUES ("Blond Om Van Te Houwen", 1), ("Tripel", 1), ("Dubbel", 1), ("Blond", 1), ("Kelk", 1), ("Water en wijn", 1), ("Doctor Who", 1), ("Suits", 1), ("The Good Place", 1);
INSERT INTO names (name) VALUES ("Wouter"), ("Sylvia"), ("José"), ("Martien"), ("Martijn"), ("Jesper"), ("Marcia");