CREATE TABLE `settings` ( `word_count` INTEGER NOT NULL);
CREATE TABLE `lists` ( `_id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `name` VARCHAR (255) NOT NULL, `selected` BOOLEAN DEFAULT 1 );
CREATE TABLE `words` ( `_id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE, `word` VARCHAR (255) NOT NULL, `selected` BOOLEAN DEFAULT 1, `list_id` INTEGER NOT NULL, CONSTRAINT fk_list_id FOREIGN KEY (list_id) REFERENCES lists (_id) ON DELETE CASCADE );
INSERT INTO settings (word_count) VALUES (1);
INSERT INTO lists (_id, name, selected) VALUES (2, 'Kerst', 1);
INSERT INTO words (word, list_id) VALUES ("Piek", 2), ("Muziek", 2), ("Liedjes", 2), ("Kleurtjes", 2), ("Zak van kerstman", 2), ("Kerstboom", 2), ("Kalkoen", 2), ("Chocolaatjes", 2);
INSERT INTO words (word, list_id) VALUES ("Lelijke trui", 2), ("Kersttrui", 2), ("Kerstsok", 2), ("Maretak", 2), ("Zwanemeer", 2), ("Muziekdoosje", 2), ("Schuddebol", 2), ("Advocaat", 2);
INSERT INTO words (word, list_id) VALUES ("Schaatsbaan", 2), ("Kerstplaatjes", 2), ("Kerstpostzegel", 2), ("Kerstkransjes", 2), ("Kerstpakket", 2), ("Noordpool", 2), ("Kerstmarkt", 2), ("Glühwein", 2);
INSERT INTO words (word, list_id) VALUES ("Kerststress", 2), ("Kerstdieren", 2), ("Kerstsloffen", 2), ("Kerstkleding", 2), ("Sneeuwvlokjes", 2), ("Kerstdoos", 2), ("Steenkool", 2), ("Koren", 2);
INSERT INTO words (word, list_id) VALUES ("Kerstdiner", 2), ("Kerstontbijt", 2), ("Kersthapjes", 2), ("Wanten", 2), ("Glitters", 2), ("Kerstservies", 2), ("Kerstmok", 2), ("Zuurstokjes", 2);
INSERT INTO words (word, list_id) VALUES ("Oud op nieuw", 2), ("Nieuwjaar", 2), ("Kerststropdas", 2), ("Kerstoorbel", 2), ("Kerktoren", 2), ("Denneboom", 2), ("Rendier", 2), ("Baard", 2);
INSERT INTO words (word, list_id) VALUES ("Vuurwerk", 2), ("Kerstmusical", 2), ("Kerstpost", 2), ("Strikjes", 2), ("Notenkraker", 2), ("Nachtmis", 2), ("Scrooge", 2), ("Kerstwens", 2);
INSERT INTO words (word, list_id) VALUES ("Decemberzegels", 2), ("Slagroom", 2), ("Marshmallows", 2), ("Chocolademelk", 2), ("Glitterjurk", 2), ("Melk en koekjes", 2), ("Kerstgedachte", 2), ("Charles Dickens", 2);
INSERT INTO words (word, list_id) VALUES ("Hemelsemodder", 2), ("Kerstverhaal", 2), ("Bijbel", 2), ("Paddestoel", 2), ("Bethlehem", 2), ("Nazareth", 2), ("Advent", 2), ("Adventskalender", 2);
INSERT INTO words (word, list_id) VALUES ("Jezus", 2), ("Kerstman", 2), ("Kerstmis", 2), ("Geluks koekje", 2), ("Druipkaars", 2), ("God", 2), ("Adventskaars", 2), ("Adventskrans", 2);
INSERT INTO words (word, list_id) VALUES ("Kerstballen", 2), ("Rood", 2), ("Groen", 2), ("Goud", 2), ("Zilver", 2), ("Cadeautjes", 2), ("Sneeuw", 2), ("Ster", 2);
INSERT INTO words (word, list_id) VALUES ("Arreslee", 2), ("Kerk", 2), ("Rudolf", 2), ("Klokjes", 2), ("Slingers", 2), ("Lekker eten", 2), ("Chocolade balletjes", 2), ("Snoepjes", 2);
INSERT INTO words (word, list_id) VALUES ("Engel", 2), ("Elfjes", 2), ("Kerstelven", 2), ("Denneappel", 2), ("Kribbe", 2), ("Ezel", 2), ("Os", 2), ("Schaapjes", 2);
INSERT INTO words (word, list_id) VALUES ("Licht", 2), ("Gezellig", 2), ("Open haard", 2), ("Familie", 2), ("Kersttrein", 2), ("Kerstbel", 2), ("Belletjes", 2), ("Kerststukje", 2);
INSERT INTO words (word, list_id) VALUES ("Kerstnacht", 2), ("Kerstavond", 2), ("Kerstfilms", 2), ("Kerststal", 2), ("Draaimolen", 2), ("Sneeuwpop", 2), ("Witte kerst", 2), ("Wandelen", 2);
INSERT INTO words (word, list_id) VALUES ("Engeltjes van de deken", 2), ("Kerstmuts", 2), ("Kerstkoekjes", 2), ("Kerststol", 2), ("Kerstversiering", 2), ("Inpakpapier", 2), ("Kersttekeningen", 2), ("Kerstkaarten", 2);
INSERT INTO words (word, list_id) VALUES ("Kerstvrouw", 2), ("Hemel", 2), ("Vallende ster", 2), ("Herders", 2), ("Kameel", 2), ("Kaarsen", 2), ("Gourmetten", 2), ("Houtvuurtje", 2);
INSERT INTO words (word, list_id) VALUES ("Houtkachel", 2), ("Lammetta", 2), ("Engelenhaar", 2);
INSERT INTO lists (_id, name, selected) VALUES (3, 'Kerst liedjes', 1);
INSERT INTO words (word, list_id) VALUES ("All I want for Christmas is you", 3), ("Last Christmas", 3), ("Why couldn’t it be Christmas everyday?", 3), ("Shake up Christmas", 3);
INSERT INTO words (word, list_id) VALUES ("Santa tell me", 3), ("Hallelujah", 3), ("Driving home for Christmas", 3), ("Do they know it’s Christmas", 3);
INSERT INTO words (word, list_id) VALUES ("It’s the most wonderfull time of the year", 3), ("Underneath the Christmastree", 3), ("Santa Clause is comin’ to town", 3), ("White Christmas", 3);
INSERT INTO words (word, list_id) VALUES ("Thank God it’s Christmas", 3), ("Sleigh ride", 3), ("Let it snow!", 3), ("It’s beginning to look a lot like Christmas", 3);
INSERT INTO words (word, list_id) VALUES ("Jingle bell rock", 3), ("My only wish", 3), ("Rudolph the red nosed reindeer", 3), ("Mistletoe", 3);
INSERT INTO words (word, list_id) VALUES ("One wish", 3), ("Have yourself a merry little Christmas", 3), ("Wonderfull Christmastime", 3), ("Frosty the snowman", 3);
INSERT INTO words (word, list_id) VALUES ("Everyday is Christmas", 3), ("Merry x-mas everybody", 3), ("Feliz Navidad", 3), ("A holly jolly Christmas", 3);
INSERT INTO words (word, list_id) VALUES ("Joy to the world", 3), ("Lonely this Christmas", 3), ("You put the X in Christmas", 3), ("2000 Miles", 3), ("Flappie", 3);
INSERT INTO lists (_id, name, selected) VALUES (4, 'Kerst films', 0);
INSERT INTO words (word, list_id) VALUES ("Home alone", 4), ("Love actually", 4), ("Frozen", 4), ("The holiday", 4), ("Call me Clause", 4), ("A Christmas Carol", 4);
INSERT INTO words (word, list_id) VALUES ("Miracle on 34th Street", 4), ("A princess for Christmas", 4), ("November Christmas", 4), ("Silent Night", 4), ("Arthur Christmas", 4), ("How the Grinch stole Christmas", 4);
INSERT INTO words (word, list_id) VALUES ("The Polar Express", 4), ("Rise of the Guardians", 4), ("Gremlins", 4), ("Bad Santa", 4), ("The Santa Clause", 4), ("Elf", 4), ("Christmas with Holly", 4);